import { MD3Colors } from 'react-native-paper/lib/typescript/types';

const baseColors = {
  primary: '#1E90FF',
  secondary: '#4CAF50',
  error: '#FF3B30',
};

export const colors: { light: MD3Colors; dark: MD3Colors } = {
  light: {
    primary: baseColors.primary,
    onPrimary: '#FFFFFF',
    primaryContainer: '#E3F2FD',
    onPrimaryContainer: '#1565C0',
    secondary: baseColors.secondary,
    onSecondary: '#FFFFFF',
    secondaryContainer: '#E8F5E9',
    onSecondaryContainer: '#2E7D32',
    tertiary: '#9C27B0',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#F3E5F5',
    onTertiaryContainer: '#7B1FA2',
    error: baseColors.error,
    onError: '#FFFFFF',
    errorContainer: '#FFEBEE',
    onErrorContainer: '#D32F2F',
    background: '#FFFFFF',
    onBackground: '#000000',
    surface: '#F5F5F5',
    onSurface: '#000000',
    surfaceVariant: '#EEEEEE',
    onSurfaceVariant: '#666666',
    outline: '#E0E0E0',
    outlineVariant: '#BDBDBD',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#121212',
    inverseOnSurface: '#FFFFFF',
    inversePrimary: '#82B1FF',
    elevation: {
      level0: 'transparent',
      level1: '#F5F5F5',
      level2: '#EEEEEE',
      level3: '#E0E0E0',
      level4: '#BDBDBD',
      level5: '#9E9E9E',
    },
    surfaceDisabled: '#BDBDBD',
    onSurfaceDisabled: '#757575',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  dark: {
    primary: baseColors.primary,
    onPrimary: '#FFFFFF',
    primaryContainer: '#1565C0',
    onPrimaryContainer: '#E3F2FD',
    secondary: baseColors.secondary,
    onSecondary: '#FFFFFF',
    secondaryContainer: '#2E7D32',
    onSecondaryContainer: '#E8F5E9',
    tertiary: '#9C27B0',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#7B1FA2',
    onTertiaryContainer: '#F3E5F5',
    error: baseColors.error,
    onError: '#FFFFFF',
    errorContainer: '#D32F2F',
    onErrorContainer: '#FFEBEE',
    background: '#121212',
    onBackground: '#FFFFFF',
    surface: '#1E1E1E',
    onSurface: '#FFFFFF',
    surfaceVariant: '#2C2C2C',
    onSurfaceVariant: '#BBBBBB',
    outline: '#2C2C2C',
    outlineVariant: '#424242',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#FFFFFF',
    inverseOnSurface: '#000000',
    inversePrimary: '#1565C0',
    elevation: {
      level0: 'transparent',
      level1: '#1E1E1E',
      level2: '#222222',
      level3: '#242424',
      level4: '#272727',
      level5: '#2C2C2C',
    },
    surfaceDisabled: '#424242',
    onSurfaceDisabled: '#757575',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
}; 